name: Add Package
on:
  workflow_dispatch:
    inputs:
      package_url:
        type: string
        description: Package URL
      package_name:
        type: string
        description: Package Name

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jmbarne3/satis-add-package@v1
        with:
          token: ${{ secrets.BOT_SATIS_TOKEN }}
          package_url: ${{ inputs.package_url }}
          package_name: ${{ inputs.package_name }}
      - env:
          GIT_EMAIL: os-downtime-bot@googlegroups.com
          GIT_NAME: os-downtime-bot
          PACKAGE_NAME: ${{ inputs.package_name }}
        run: |
          git config user.name $GIT_NAME
          git config user.email $GIT_EMAIL
          git add docs/
          git add satis.json
          git commit -m "Added $PACKAGE_NAME to repository."
          git push
